export const FETCH_DIRECTION_SEARCH_REQUEST = 'FETCH_DIRECTION_SEARCH_REQUEST';
export const FETCH_DIRECTION_SEARCH_FAILURE = 'FETCH_DIRECTION_SEARCH_FAILURE';
export const FETCH_DIRECTION_SEARCH_SUCCESS = 'FETCH_DIRECTION_SEARCH_SUCCESS';
export const FETCH_DIRECTION_SEARCH_CLEAR = 'FETCH_DIRECTION_SEARCH_CLEAR';