export const FETCH_SELECT_ROUTE = 'FETCH_SELECT_ROUTE';
export const FETCH_SEATS_REQUEST = 'FETCH_SEATS_REQUEST';
export const FETCH_SEATS_SUCCESS = 'FETCH_SEATS_SUCCESS';
export const FETCH_SEATS_FAILURE = 'FETCH_SEATS_FAILURE';
